// <auto-generated />
namespace _744Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedDB_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedDB_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201803261826061_added DB_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
