// <auto-generated />
namespace _744Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddIPaddresscolunm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIPaddresscolunm));
        
        string IMigrationMetadata.Id
        {
            get { return "201802110224262_Add IP address colunm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
