// <auto-generated />
namespace _744Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class t3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(t3));
        
        string IMigrationMetadata.Id
        {
            get { return "201804200140099_t3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
